routes/admin.php
<?php
// For Language
Route::get('setlocale/{locale}', function ($locale) {
    if (in_array($locale, \Config::get('app.locales'))) {
        Session::put('locale', $locale);
    }
    return redirect()->back();
});

Route::group(['prefix' => 'admin','namespace'=>'admin'], function () {

    // Without Login
    Route::get('login', 'AuthController@login');
    Route::post('login/store', 'AuthController@store');

    // Must Login
    Route::group(['middleware' => 'admin:webAdmin'], function(){

        ######################### Home #################################
        Route::get('/', 'HomeController@index');
        Route::get('/index', 'HomeController@index');

        ######################### Logout #################################
        Route::get('/logout', 'AuthController@logout');

        ######################### Admins #################################
        Route::get('admins', 'AdminController@index');
        Route::get('admins/create', 'AdminController@create');
        Route::post('admins/store', 'AdminController@store');
        Route::get('admins/edit/{id?}', 'AdminController@edit');
        Route::patch('admins/update/{id?}', 'AdminController@update');
        Route::post('admins/destroy', 'AdminController@destroy');

        ######################### Settings #################################
        Route::resource('/settings', 'SettingController');

        ######################### Videos #################################
        Route::resource('/videos', 'VideoController');
        Route::post('videos/delete', 'VideoController@destroy');

        ######################### Members #################################
        Route::resource('/members', 'MemberController');
        Route::post('members/delete', 'MemberController@destroy');
        Route::get('members/active/{id}', 'MemberController@active');


    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// langauge (Arabic - English)
Route::get('setlocale/{locale}', function ($locale) {
    if (in_array($locale, \Config::get('app.locales'))) {
        Session::put('locale', $locale);
    }
    return redirect()->back();
});

Route::group(['namespace'=>'frontend'], function () {
    ######################### Home #################################
    Route::get('/', 'HomeController@index');
    Route::get('/index', 'HomeController@index');

    ######################### Members #################################
    Route::resource('/members', 'MemberController');
});

//ClearCache
Route::get('/clearcache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    return "Cleared!";
});

app/Http/Controllers/admin/SettingController.php
<?php
namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cache;
use App\Model\Setting;


class SettingController extends Controller
{
    private $rules = [
        'key'     => 'required|max:250',
        'type'     => 'required|in:text,longtext,image',
    ];

    private $rulesUpdate = [
        'value'     => 'required',
    ];

    private $rulesUpdateImage = [
        'value'     => 'required|image',
    ];

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $setting = Setting::all();
        return view('admin.settings.create', [
            'title' => "Create setting",
            'setting' => $setting,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validate($request, $this->rules);
        $setting = Setting::create($data);
        session()->flash('success', "add Successfully");
        return redirect()->route('settings.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

     public function index()
     {
         $pages = Setting::all();
         return view('admin.settings.index', [
             'title' => trans('admin.settings'),
             'index' => $pages,
         ]);
     }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $setting = Setting::findOrFail($id);
        return view('admin.settings.edit', [
                'title' => trans('admin.edit settings'),
                'edit'  => $setting,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $setting = Setting::findOrFail($id);
        Cache::forget($setting->key);

        if ($setting->type == "image") {
            $data = $this->validate($request, $this->rulesUpdateImage);
        if ($request->hasFile('value')) {
            if (file_exists(public_path('uploads/settings' . $setting->value))) {
                @unlink(public_path('uploads/settings' . $setting->value));
            }
            $data['value'] = UploadImages('settings', $request->file('value'));
        }
        $data = array_merge($request->except('_token', '_method'), $data);
      }else{
        $data = $this->validate($request, $this->rulesUpdate);
        $data['value'] = $request->value;
      }

        $setting->update($data);

        session()->flash('success', trans('admin.edit Successfully'));
        return redirect()->route('settings.index');
    }



}

resources/views/admin/settings/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="row page-titles">
        <div class="col-md-6 col-8 align-self-center">
            <h3 class="text-themecolor m-b-0 m-t-0">{{$title}}</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">{{$title}}</li>
            </ol>
        </div>

    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-block">
                    <h4 class="card-title">{{$title}}</h4>
                    <form class="form-material m-t-40" method="post"  action="{{ route('settings.store') }}"  enctype="multipart/form-data">
                      @csrf


                        <div class="form-group {{ $errors->has('key') ? ' has-error has-danger' : '' }} ">
                            <label>Key<span style="color:red">*</span></label>
                            <input type="text"  value="{{ old('key') }}" name="key" class="form-control form-control-line"  required>
                            @if ($errors->has('key'))
                                <span class="help-block">
                                    <strong class="help-block">{{ $errors->first('key') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group {{ $errors->has('type') ? ' has-error has-danger' : '' }} ">
                            <label>Type<span style="color:red">*</span></label>
                            <select  name="type" class="form-control"  required>
                              <option value="text" {{ old('type') == 'text' ? 'selected' : '' }}>Text</option>
                              <option value="longtext" {{ old('type') == 'longtext' ? 'selected' : '' }}>Long Text</option>
                              <option value="image" {{ old('type') == 'image' ? 'selected' : '' }}>Image</option>
                            </select>
                            @if ($errors->has('type'))
                                <span class="help-block">
                                    <strong class="help-block">{{ $errors->first('type') }}</strong>
                                </span>
                            @endif
                        </div>





                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-2 col-md-10">
                                    <button type="submit" class="btn btn-primary">Add</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/settings/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block">{{ $title }}</h3>
            <div class="row breadcrumbs-top d-inline-block">
                <div class="breadcrumb-wrapper col-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ aurl("/settings") }}">{{ trans("admin.settings") }}</a>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <!-- Striped row layout section start -->
        <section id="striped-row-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title" id="horz-layout-icons">{{ $title }}</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="close"><i class="ft-x"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collpase show">
                            <div class="card-body">
                    <form class="form-material m-t-40" method="post"  action="{{ route('settings.update', [$edit->id]) }}"  enctype="multipart/form-data">
                      @csrf
                      @method('PATCH')
                      <div class="form-body">
                      @if ($edit->type == "text")
                        <div class="form-group {{ $errors->has('value') ? ' has-error has-danger' : '' }}">
                            <label>{{ trans('admin.'.$edit->key) }}<span style="color:red">*</span></label>
                            <input type="text" class="form-control" name="value" value="{{ $edit->value }}">
                            @if ($errors->has('value'))
                                <span class="help-block">
                                    <strong class="help-block">{{ $errors->first('value') }}</strong>
                                </span>
                            @endif
                        </div>


                      @elseif ($edit->type == "longtext")
                          <div class="form-group {{ $errors->has('value') ? ' has-error has-danger' : '' }}">
                            <label>{{ trans('admin.'.$edit->key) }}<span style="color:red">*</span></label>
                            <textarea class="form-control" rows="4"  name="value" >{{ $edit->value }}</textarea>
                            @if ($errors->has('value'))
                                <span class="help-block">
                                    <strong class="help-block">{{ $errors->first('value') }}</strong>
                                </span>
                            @endif
                          </div>


                      @else
                          <div class="form-group row">
                              <label class="col-md-3 label-control" for="timesheetinput2">{{ trans('admin.image') }}</label>
                              <div class="col-md-9">
                                  <div class="position-relative has-icon-left">
                                  <img src="{{ asset('uploads/'.$edit->value) }}" title="value" style="height:100px; width:200px;" />
                                  </div>
                              </div>
                          </div>
                          <div class="form-group row">
                              <label class="col-md-3 label-control" for="timesheetinput2">{{ trans('admin.image') }}</label>
                              <div class="col-md-9">
                                  <div class="position-relative has-icon-left">
                                      <input type="file"  class="form-control"
                                      name="value" >
                                      <div class="form-control-position">
                                          <i class="la la-briefcase"></i>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      @endif
                                <div class="form-actions right">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="la la-check-square-o"></i> {{ trans("admin.edit") }}
                                    </button>
                                </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
</div>
@endsection
@section('scripts')
    <script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript">
        CKEDITOR.replace('value', {
            language: 'ar',
        });
    </script>
@endsection

resources/views/admin/settings/index.blade.php
@extends('admin.layouts.app')


@section('content')
    <div class="content-header row">
      <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">{{ $title }}</h3>
        <div class="row breadcrumbs-top d-inline-block">
          <div class="breadcrumb-wrapper col-12">

          </div>
        </div>
      </div>
    </div>
    <div class="content-body">
      <!-- HTML5 export buttons table -->
      <!-- Column selectors table -->
      <section id="column-selectors">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">{{ $title }}</h4>
                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                <div class="heading-elements">
                  <ul class="list-inline mb-0">
                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                    <li><a data-action="close"><i class="ft-x"></i></a></li>
                  </ul>
                </div>
              </div>
              <div class="card-content collapse show">
                <div class="card-body card-dashboard">
                  <table class="table table-striped table-bordered dataex-html5-selectors">
                    <thead>
                      <tr>
                          <th>{{ trans('admin.key') }}</th>
                          <th>{{ trans('admin.value') }}</th>
                          <th>{{ trans('admin.edit') }}</th>
                      </tr>
                    </thead>
                    <tbody>
                        @foreach ($index as $i)
                            <tr>
                                <td>{{ trans('admin.'.$i->key) }}</td>
                              @if ($i->type == "image")
                                <td><img src="{{ asset('uploads/'.$i->value) }}" style="height:100px;" ></td>
                              @else
                                <td>{!! str_limit($i->value, $limit = 250, $end = '...') !!}</td>
                              @endif
                                <td>
                                    <a href="{{ route('settings.edit', [$i->id]) }}" class="btn btn-secondary btn-min-width mr-1 mb-1"><i class="ft-edit"></i> {{ trans('admin.edit') }}</a>
                                </td>

                            </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                      <tr>
                          <th>{{ trans('admin.key') }}</th>
                          <th>{{ trans('admin.value') }}</th>
                          <th>{{ trans('admin.edit') }}</th>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!--/ Column selectors table -->
</div>


@endsection