routes/admin.php
<?php
// For Language
Route::get('setlocale/{locale}', function ($locale) {
    if (in_array($locale, \Config::get('app.locales'))) {
        Session::put('locale', $locale);
    }
    return redirect()->back();
});

Route::group(['prefix' => 'admin','namespace'=>'admin'], function () {

    // Without Login
    Route::get('login', 'AuthController@login');
    Route::post('login/store', 'AuthController@store');

    // Must Login
    Route::group(['middleware' => 'admin:webAdmin'], function(){

        ######################### Home #################################
        Route::get('/', 'HomeController@index');
        Route::get('/index', 'HomeController@index');

        ######################### Logout #################################
        Route::get('/logout', 'AuthController@logout');

        ######################### Admins #################################
        Route::get('admins', 'AdminController@index');
        Route::get('admins/create', 'AdminController@create');
        Route::post('admins/store', 'AdminController@store');
        Route::get('admins/edit/{id?}', 'AdminController@edit');
        Route::patch('admins/update/{id?}', 'AdminController@update');
        Route::post('admins/destroy', 'AdminController@destroy');

        ######################### Settings #################################
        Route::resource('/settings', 'SettingController');

        ######################### Videos #################################
        Route::resource('/videos', 'VideoController');
        Route::post('videos/delete', 'VideoController@destroy');

        ######################### Members #################################
        Route::resource('/members', 'MemberController');
        Route::post('members/delete', 'MemberController@destroy');
        Route::get('members/active/{id}', 'MemberController@active');


    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// langauge (Arabic - English)
Route::get('setlocale/{locale}', function ($locale) {
    if (in_array($locale, \Config::get('app.locales'))) {
        Session::put('locale', $locale);
    }
    return redirect()->back();
});

Route::group(['namespace'=>'frontend'], function () {
    ######################### Home #################################
    Route::get('/', 'HomeController@index');
    Route::get('/index', 'HomeController@index');

    ######################### Members #################################
    Route::resource('/members', 'MemberController');
});

//ClearCache
Route::get('/clearcache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    return "Cleared!";
});

app/Http/Controllers/admin/VideoController.php
<?php
namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Video;
use App\Http\Requests\video\VideoStoreRequest;
use App\Http\Requests\video\VideoUpdateRequest;

class VideoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.videos.index',[
            'title'=>trans('admin.Videos'),
            'videos'=>Video::get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.videos.create',[
            'title'=>trans('admin.add video'),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     public function store(VideoStoreRequest $request)
     {

         $data = $request->validated();
         $admin = Video::Create($data);

         return redirect(aurl('/videos'))->with(['success' => trans('admin.add Successfully')]);
     }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $video = Video::findOrFail($id);
        return view('admin.videos.edit', [
            'title' => trans("admin.edit video") . ' : ' . $video->title,
            'video'  => $video,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function update(VideoUpdateRequest $request,$id)
     {

         $video = Video::findOrFail($id);
         //Validation
         $data = $request->validated();
         //Update Video
         $video->update($data);
         // Success Message
         session()->flash('success', trans("admin.edit Successfully"));
         return  redirect('admin/videos');
     }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy()
    {
        if (request()->filled('id')) {
            $id = request()->id;
            Video::findOrFail($id)->delete();
        }
    }
}

resources/views/admin/videos/create.blade.php
@extends('admin.layouts.app')

@section('content')

<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">{{ $title }}</h3>

    </div>
</div>
<div class="content-body">
    <!-- Striped row layout section start -->
    <section id="striped-row-form-layouts">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title" id="horz-layout-icons">{{ $title }}</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="close"><i class="ft-x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collpase show">
                        <div class="card-body">
                            <form class="form form-horizontal striped-rows form-bordered" method="post"
                                action="{{ route('videos.store') }}">
                                @csrf
                                <div class="form-body">

                                    <!-- Add Title -->
                                    <div class="form-group row">
                                        <label class="col-md-3 label-control"
                                            for="timesheetinput2">{{ trans('validation.attributes.title') }}</label>
                                        <div class="col-md-9">
                                            <div class="position-relative has-icon-left">
                                                <input type="text" required class="form-control"
                                                    placeholder="{{ trans('validation.attributes.title') }}" name="title"
                                                    value="{{ old('title') }}">
                                                <div class="form-control-position">
                                                    <i class="ft-tag"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Add Youtube Link -->
                                    <div class="form-group row">
                                        <label class="col-md-3 label-control"
                                            for="timesheetinput2">{{ trans('validation.attributes.link') }}</label>
                                        <div class="col-md-9">
                                            <div class="position-relative has-icon-left">
                                                <input type="text" required class="form-control"
                                                    placeholder="{{ trans('validation.attributes.link') }}" name="link"
                                                    value="{{ old('link') }}">
                                                <div class="form-control-position">
                                                    <i class="ft-tag"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <!-- Save Button -->
                                <div class="form-actions right">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fas fa-save"></i> {{ trans("admin.save") }}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@endsection

resources/views/admin/videos/edit.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block">{{ $title }}</h3>

        </div>
    </div>
    <div class="content-body">
        <!-- Striped row layout section start -->
        <section id="striped-row-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title" id="horz-layout-icons">{{ $title }}</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="close"><i class="ft-x"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form class="form form-horizontal striped-rows form-bordered" method="post"  action="{{ route('videos.update', [$video->id]) }}">
                                    @csrf
                                    @method('PATCH')
                                    <div class="form-body">

                                        <!-- Edit Title -->
                                        <div class="form-group row">
                                            <label class="col-md-3 label-control"
                                                for="timesheetinput2">{{ trans('validation.attributes.title') }}</label>
                                            <div class="col-md-9">
                                                <div class="position-relative has-icon-left">
                                                    <input type="text" required class="form-control"
                                                        placeholder="{{ trans('validation.attributes.title') }}" name="title"
                                                        value="{{ $video->title }}">
                                                    <div class="form-control-position">
                                                        <i class="ft-tag"></i>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <!-- Edit Youtube Link -->
                                        <div class="form-group row">
                                            <label class="col-md-3 label-control"
                                                for="timesheetinput2">{{ trans('validation.attributes.link') }}</label>
                                            <div class="col-md-9">
                                                <div class="position-relative has-icon-left">
                                                    <input type="text" required class="form-control"
                                                        placeholder="{{ trans('validation.attributes.link') }}" name="link"
                                                        value="{{ $video->link }}">
                                                    <div class="form-control-position">
                                                        <i class="ft-tag"></i>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Edit Button -->
                                    <div class="form-actions right">
                                        <button type="submit" class="btn btn-primary">
                                            <i class="la la-check-square-o"></i> {{ trans("admin.edit") }}
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection

resources/views/admin/videos/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="content-body">
    <!-- HTML5 export buttons table -->
    <!-- Column selectors table -->
    <section id="column-selectors">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">{{ $title }}</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="close"><i class="ft-x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard">
                            <table class="table table-striped table-bordered dataex-html5-selectors">
                                <thead>
                                    <tr>
                                        <th>{{ trans('validation.attributes.title') }}</th>
                                        <th>{{ trans('validation.attributes.link') }}</th>
                                        <th>{{ trans('admin.actions') }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($videos as $video)
                                    <tr id="show_{{ $video->id }}">
                                        <td>{{ $video->title }}</td>
                                        <td>{{ $video->link }}</td>
                                        <td>
                                            <a href="{{ aurl('/videos/'.$video->id.'/edit') }}" class="btn btn-secondary btn-min-width mr-1 mb-1"><i class="ft-edit"></i> {{ trans('admin.edit') }}</a>
                                            <input type="hidden" value="{{ csrf_token() }}" id="csrf_token" />
                                            <button class="btn btn-danger btn-min-width btn-glow mr-1 mb-1" onclick="DeleteRow({{$video->id}})"><i class="ft-delete"></i> {{ trans('admin.delete') }}</button>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>{{ trans('validation.attributes.title') }}</th>
                                        <th>{{ trans('validation.attributes.link') }}</th>
                                        <th>{{ trans('admin.actions') }}</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/ Column selectors table -->
</div>
@endsection

@section('scripts') @if (session()->get('locale') == "ar")
<script>
    function DeleteRow(id) {
                     event.preventDefault();
                     swal({
                         title: "هل انت متأكد من الحذف ؟",
                         text: "في حالة الموافقة على الحذف سيتم حذف البيانات نهائيا",
                         icon: "warning",
                         buttons: {
                             cancel: {
                                 text: "لا أريد الحذف",
                                 value: null,
                                 visible: true,
                                 className: "",
                                 closeModal: false,
                             },
                             confirm: {
                                 text: "نعم أريد الحذف",
                                 value: true,
                                 visible: true,
                                 className: "",
                                 closeModal: false
                             }
                         }
                     })
                     .then((isConfirm) => {
                         if (isConfirm) {
                          $.ajax({
                              type: 'post',
                              url: "{{aurl("/videos/delete/")}}",
                              data: {
                                  '_token': $('#csrf_token').val(),
                                  'id': id,
                              },

                          });
                          $('#show_' + id).remove();
                             swal("تم الحذف!", "البيانات تم حذفها بنجاح", "success");
                         } else {
                             swal("تم الغاء الطلب", "لم يتم حذف الداتا", "error");
                         }
                     });

              }

</script>
@else
<script>
    function DeleteRow(id) {
                     event.preventDefault();
                     swal({
                         title: "Are you sure?",
                         text: "You will not be able to recover this imaginary file!",
                         icon: "warning",
                         buttons: {
                             cancel: {
                                 text: "No, cancel",
                                 value: null,
                                 visible: true,
                                 className: "",
                                 closeModal: false,
                             },
                             confirm: {
                                 text: "Yes, delete it!",
                                 value: true,
                                 visible: true,
                                 className: "",
                                 closeModal: false
                             }
                         }
                     })
                     .then((isConfirm) => {
                         if (isConfirm) {
                          $.ajax({
                              type: 'post',
                              url: "{{aurl("/videos/delete/")}}",
                              data: {
                                  '_token': $('#csrf_token').val(),
                                  'id': id,
                              },

                          });
                          $('#show_' + id).remove();
                             swal("Deleted!", "Your data has been deleted.", "success");
                         } else {
                             swal("Cancelled", "Your data is safe", "error");
                         }
                     });

              }

</script>
@endif
@endsection