routes/admin.php
<?php
// For Language
Route::get('setlocale/{locale}', function ($locale) {
    if (in_array($locale, \Config::get('app.locales'))) {
        Session::put('locale', $locale);
    }
    return redirect()->back();
});

Route::group(['prefix' => 'admin','namespace'=>'admin'], function () {

    // Without Login
    Route::get('login', 'AuthController@login');
    Route::post('login/store', 'AuthController@store');

    // Must Login
    Route::group(['middleware' => 'admin:webAdmin'], function(){

        ######################### Home #################################
        Route::get('/', 'HomeController@index');
        Route::get('/index', 'HomeController@index');

        ######################### Logout #################################
        Route::get('/logout', 'AuthController@logout');

        ######################### Admins #################################
        Route::get('admins', 'AdminController@index');
        Route::get('admins/create', 'AdminController@create');
        Route::post('admins/store', 'AdminController@store');
        Route::get('admins/edit/{id?}', 'AdminController@edit');
        Route::patch('admins/update/{id?}', 'AdminController@update');
        Route::post('admins/destroy', 'AdminController@destroy');

        ######################### Settings #################################
        Route::resource('/settings', 'SettingController');

        ######################### Videos #################################
        Route::resource('/videos', 'VideoController');
        Route::post('videos/delete', 'VideoController@destroy');

        ######################### Members #################################
        Route::resource('/members', 'MemberController');
        Route::post('members/delete', 'MemberController@destroy');
        Route::get('members/active/{id}', 'MemberController@active');


    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// langauge (Arabic - English)
Route::get('setlocale/{locale}', function ($locale) {
    if (in_array($locale, \Config::get('app.locales'))) {
        Session::put('locale', $locale);
    }
    return redirect()->back();
});

Route::group(['namespace'=>'frontend'], function () {
    ######################### Home #################################
    Route::get('/', 'HomeController@index');
    Route::get('/index', 'HomeController@index');

    ######################### Members #################################
    Route::resource('/members', 'MemberController');
});

//ClearCache
Route::get('/clearcache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    return "Cleared!";
});

app/Http/Controllers/admin/MemberController.php
<?php
namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Member;
use App\Model\Sport;
use App\Http\Requests\member\MemberStoreRequest;
use App\Http\Requests\member\MemberUpdateRequest;
use EloquentBuilder;

class MemberController extends Controller
{
    /**
     * [Filter Function]
     * @param string $value [description]
     */
    public function filter($member)
    {

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Get Sports For Select
        $sports = Sport::get();

        //Make Advanced Filter Search
        $member = EloquentBuilder::to(
                    Member::class,
                    request()->all()
                 );
        //End Search
        $count = $member->count(); // For Get Count of Members
        $members = $member->with('sport')->paginate(30);
        return view('admin.members.index',[
            'title'=>trans('admin.Members'),
            'members'=>$members,
            'sports'=>$sports,
            'count'=>$count
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sports = Sport::get();
        return view('admin.members.create',[
            'title'  =>trans('admin.add member'),
            'sports' => $sports
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     public function store(MemberStoreRequest $request)
     {

         $data = $request->validated();
         //If Membership is Planes make membership wait active
         $request->sport_id == "2" ? $data['status'] = '2' : $data['status'] = '1 ';
         //Upload Image
         $destination = "members/" . date("Y") . "/" . date("m");
         $data['image'] = UploadImages($destination, $request->file('image'));
         //Create New Member
         Member::Create($data);
         //Return Success Message
         return redirect(aurl('/members'))->with(['success' => trans('admin.add Successfully')]);
     }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $member = Member::findOrFail($id);
        $sports = Sport::get();
        return view('admin.members.edit', [
            'title' => trans("admin.edit member") . ' : ' . $member->name,
            'member'  => $member,
            'sports'  => $sports,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function update(MemberUpdateRequest $request,Member $member)
     {

         $member = Member::findOrFail($member->id);
         //Validation
         $data = $request->validated();
         //If Membership is Planes make membership wait active
         $request->sport_id == "2" ? $data['status'] = '2' : $data['status'] = '1 ';
         // Upload Image
         if ($request->hasFile('image')) {
             if (file_exists(public_path('uploads/' . $member->image))) {
                 @unlink(public_path('uploads/' . $member->image));
             }
             $destination = "members/" . date("Y") . "/" . date("m");
             $data['image'] = UploadImages($destination, $request->file('image'));
         }else{
              $data['image'] = $member->image;
         }
         //Update Member
         $member->update($data);
         // Success Message
         session()->flash('success', trans("admin.edit Successfully"));
         return  redirect('admin/members');
     }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy()
    {
        if (request()->filled('id')) {
            $id = request()->id;
            $member = Member::findOrFail($id);
            if (file_exists(public_path('uploads/' . $member->image))) {
                @unlink(public_path('uploads/' . $member->image));
            }
            $member->delete();
        }
    }



    /**
     * Show the form for active or deactive the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function active($id)
    {
        //Update Data
        $member = Member::findOrFail($id);
        if ($member->status == 1) {
            $member->update(['status' => '0']);
        } else {
            $member->update(['status' => '1']);
        }
        // Success Message
        session()->flash('success', trans("admin.edit Successfully"));
        return  redirect('admin/members');
    }

}

app/Http/Controllers/api/MemberController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use App\Model\Member;

class MemberController extends Controller
{
    /**
     * [Check Member]
     * @param  Request $request [id_number]
     * api_url: api/status  [method:post]
     * @return [json]           [Member data with Message]
     */
    public function index()
    {
        // search if member found and active
        $member = Member::where('status','1')->get(['id_number'])->pluck('id_number');
        // all good so return success
        return response()->json($member);
    }


}

app/Http/Controllers/frontend/MemberController.php
<?php
namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\member\MemberStoreRequest;
use App\Model\Member;
use App\Model\Visitor;
use App\Model\Sport;

class MemberController extends Controller
{

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Add New Visit If This First Visit In Today
        $user_ip = getUserIP();
        $created = date("Y-m-d");
        $visitor = Visitor::where('ip', $user_ip)->where('created',$created)->first();
        if(is_null($visitor)){
            Visitor::create(['ip' => $user_ip,'created' => $created]);
        }

        $sports = Sport::get();
        return view('front.members.create',compact('sports'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(MemberStoreRequest $request)
    {
        $data = $request->validated();
        //If Membership is Planes make membership wait active
        $request->sport_id == "2" ? $data['status'] = '2' : $data['status'] = '1 '; //2 Not Active && 1 Active
        //Upload Image
        $destination = "members/" . date("Y") . "/" . date("m");
        $data['image'] = UploadImages($destination, $request->file('image'));
        //Create New Member
        Member::Create($data);
        //Return Success Message
        return redirect()->back()->with(['success' => trans('admin.subscription_message')]);
    }

}

resources/views/admin/members/create.blade.php
@extends('admin.layouts.app')

@section('content')

<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">{{ $title }}</h3>

    </div>
</div>
<div class="content-body">
    <!-- Striped row layout section start -->
    <section id="striped-row-form-layouts">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title" id="horz-layout-icons">{{ $title }}</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="close"><i class="ft-x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collpase show">
                        <div class="card-body">
                            <form class="form form-horizontal striped-rows form-bordered" method="post"
                                action="{{ route('members.store') }}" enctype="multipart/form-data">
                                @csrf
                                <div class="form-body">

                                    <!-- Add Full Name -->
                                    <div class="form-group row">
                                        <label class="col-md-3 label-control"
                                            for="timesheetinput2">{{ trans('validation.attributes.name') }}</label>
                                        <div class="col-md-9">
                                            <div class="position-relative has-icon-left">
                                                <input type="text" required class="form-control"
                                                    placeholder="{{ trans('validation.attributes.name') }}" name="name"
                                                    value="{{ old('name') }}">
                                                <div class="form-control-position">
                                                    <i class="ft-tag"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Add ID Number -->
                                    <div class="form-group row">
                                        <label class="col-md-3 label-control"
                                            for="timesheetinput2">{{ trans('validation.attributes.id_number') }}</label>
                                        <div class="col-md-9">
                                            <div class="position-relative has-icon-left">
                                                <input type="number" required class="form-control"
                                                    placeholder="{{ trans('validation.attributes.id_number') }}" name="id_number"
                                                    value="{{ old('id_number') }}">
                                                <div class="form-control-position">
                                                    <i class="ft-tag"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Add Mobile -->
                                    <div class="form-group row">
                                        <label class="col-md-3 label-control"
                                            for="timesheetinput2">{{ trans('validation.attributes.mobile') }}</label>
                                        <div class="col-md-9">
                                            <div class="position-relative has-icon-left">
                                                <input type="number" required class="form-control"
                                                    placeholder="{{ trans('validation.attributes.mobile') }}" name="mobile"
                                                    value="{{ old('mobile') }}">
                                                <div class="form-control-position">
                                                    <i class="ft-tag"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Add Membership Type -->
                                    <div class="form-group row">
                                        <label class="col-md-3 label-control"
                                            for="timesheetinput2">{{ trans('validation.attributes.sport_id') }}</label>
                                        <div class="col-md-9">
                                            <div class="position-relative has-icon-left">
                                                <select
                                                  id="membershipType"
                                                  class="form-control"
                                                  required="true"
                                                  name="sport_id"
                                                >
                                                  <option value="" selected>{{ trans('validation.attributes.sport_id') }}</option>
                                                  @foreach ($sports as $sport)
                                                      <option value="{{ $sport->id }}" {{ old('sport_id') == $sport->id ? 'selected' : '' }}>{{ $sport->title }}</option>
                                                  @endforeach
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Add Gender -->
                                    <div class="form-group row">
                                        <label class="col-md-3 label-control"
                                            for="timesheetinput2">{{ trans('validation.attributes.gender') }}</label>
                                        <div class="col-md-9">
                                            <div class="position-relative has-icon-left">
                                                <select
                                                  id="genderType"
                                                  class="form-control"
                                                  required="true"
                                                  name="gender"
                                                >
                                                  <option value="" selected> {{ trans('validation.attributes.gender') }} </option>
                                                  <option value="1" {{ old('gender') == "1" ? 'selected' : '' }}> {{ trans('admin.male') }} </option>
                                                  <option value="2" {{ old('gender') == "2" ? 'selected' : '' }}> {{ trans('admin.female') }} </option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Add Nationality -->
                                    <div class="form-group row">
                                        <label class="col-md-3 label-control"
                                            for="timesheetinput2">{{ trans('validation.attributes.nationality') }}</label>
                                        <div class="col-md-9">
                                            <div class="position-relative has-icon-left">
                                                <input type="text" required class="form-control"
                                                    placeholder="{{ trans('validation.attributes.nationality') }}" name="nationality"
                                                    value="{{ old('nationality') }}">
                                                <div class="form-control-position">
                                                    <i class="ft-tag"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Add Birth Date -->
                                    <div class="form-group row">
                                        <label class="col-md-3 label-control"
                                            for="timesheetinput2">{{ trans('validation.attributes.birth_date') }}</label>
                                        <div class="col-md-9">
                                            <div class="position-relative has-icon-left">
                                                <input type="date" required class="form-control"
                                                    placeholder="{{ trans('validation.attributes.birth_date') }}" name="birth_date"
                                                    value="{{ old('birth_date') }}">
                                                <div class="form-control-position">
                                                    <i class="ft-tag"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Add Address -->
                                    <div class="form-group row">
                                        <label class="col-md-3 label-control"
                                            for="timesheetinput2">{{ trans('validation.attributes.address') }}</label>
                                        <div class="col-md-9">
                                            <div class="position-relative has-icon-left">
                                                <input type="text" required class="form-control"
                                                    placeholder="{{ trans('validation.attributes.address') }}" name="address"
                                                    value="{{ old('address') }}">
                                                <div class="form-control-position">
                                                    <i class="ft-tag"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Add Image -->
                                    <div class="form-group row">
                                        <label class="col-md-3 label-control"
                                            for="timesheetinput2">{{ trans('validation.attributes.image') }}</label>
                                        <div class="col-md-9">
                                            <div class="position-relative has-icon-left">
                                                <input type="file" required class="form-control"
                                                    name="image">
                                            </div>
                                        </div>
                                    </div>


                                </div>
                                <!-- Save Button -->
                                <div class="form-actions right">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fas fa-save"></i> {{ trans("admin.save") }}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@endsection